{{- if .Values.ingress.enabled }}
{{- $apiIsStable := eq (include "my-ghost.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "my-ghost.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "my-ghost.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "my-ghost.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- if and .Values.ingress.ingressClass (not $apiIsStable) }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
    {{- end }}
  labels:
{{ include "my-ghost.labels" . | indent 4 }}  
spec:
  {{- if and .Values.ingress.ingressClass $apiIsStable }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  rules:
  {{- if not (empty .Values.url) }}
  - host: {{ .Values.url }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
        - path: /
          {{- if $ingressSupportsPathType }}
          pathType: Prefix
          {{- end }}
          backend:
            {{- if $apiIsStable }}
            service:
              name: {{ template "my-ghost.fullname" . }}
              port:
                number: {{ .Values.service.port }}
            {{- else }}
            serviceName: {{ template "my-ghost.fullname" . }}
            servicePort: {{ .Values.service.port }}
            {{- end }}
{{- end }}
